#!/usr/bin/env ruby

require 'date'

require 'terminal-table'

require "rawbotz"
require 'rawbotz/option_parser'

options = {}

optparse = Rawbotz::OptionParser.new do |opts, options|
  opts.banner = "Usage: #{$PROGRAM_NAME} [OPTIONS] ORDER_ID"
  opts.separator ""

  opts.on("-m", "--[no]-mail") do |m|
    options[:mail] = m
  end
end
optparse.parse!
options = optparse.options

include RawgentoModels

def main options
  logger = Logger.new(STDOUT)
  logger.level = options[:verbose] ? Logger::DEBUG : Logger::INFO

  logger.debug "#{$PROGRAM_NAME} #{Rawbotz::VERSION}"

  logger.info("Checking queue")

  queue = RawgentoModels::Order.queued
  logger.info("-> #{queue.count} orders to process")

  if queue.count == 0
    logger.info("Nothing to do, exiting.")
    exit 0
  end

  order = queue.first

  logger.info("#{order.order_items.length} items in Order")

  if order.state != :new
    logger.warn("Order in state #{order.state}!")
  end
  order.update(state: :processing)

  logger.info ("#{order.order_items.processible.count} products to order.")

  mech = Rawbotz.new_mech

  # check and "merge" cart content
  #logger.debug mech.get_cart_content

  mech.login

  order_processor = Rawbotz::OrderProcessor.new(order, logger)

  order_processor.process! do |item|
    #logger.info("Do something")
  end

  # Check cart content

  #order.update(state: :ordered)

  logger.info("Finished order")

  logger.info("Checking current cart")
  diffs = order_processor.check_against_cart

  if !diffs[:perfect].empty?
    puts Terminal::Table.new title: "Perfect",
      headings: ['Product', 'In Cart'],
      rows: diffs[:perfect].map { |p,q|
        [p.local_product.remote_product.name,q]
      },
      style: {width: 60}
    puts
    puts
  end

  if !diffs[:modified].empty?
    puts Terminal::Table.new title: "Modified",
      headings: ['Product', 'Wished', 'In Cart'],
      rows: diffs[:modified].map { |p,q|
        [p.local_product.remote_product.name, p.num_wished, q]
      },
      style: {width:60}
    puts
    puts
  end

  if !diffs[:miss].empty?
    puts Terminal::Table.new title: "Missing (?)",
      :headings => ['Product', 'In Cart'],
      :rows => diffs[:miss].map{|p,q| [p.local_product.remote_product.name,q]},
      style: {width:60}
    puts
    puts
  end

  if !diffs[:under_avail].empty?
    puts Terminal::Table.new title: "Not available as such",
      :headings => ['Product', 'Wanted', 'In Cart'],
      :rows => diffs[:under_avail].map{|p,q| [p.local_product.remote_product.name,item.num_wished, q]},
      style: {width:60}
    puts
    puts
  end

  if !diffs[:extra].empty?
    puts Terminal::Table.new title: "Extra (not in rawbotz)",
      :headings => ['Product', 'In Cart'],
      :rows => diffs[:extra],
      style: {width:60}
  end

  if options[:mail]
    logger.debug("Sending mail")
    Rawbotz::mail("rawbotz order finished",
                  "Finished Order nr #{order.id}. Result: [tbd]")
  end
end

main options
exit 0
