#!/usr/bin/env ruby

require 'date'

require "rawbotz"

include RawgentoModels

def main
  RawgentoModels.establish_connection
  
  result = RawgentoDB::Query.stock(RawgentoDB.settings)
  now = DateTime.now
  
  result.each do |s|
    product = RawgentoModels::LocalProduct.find_by(product_id: s.product_id)
    if product.nil?
      puts "No such product #{s.product_id}"
    else
      product.stock_items.create(qty: s.qty, date: now)
      puts "Updated stock for #{s.product_id}"
    end
  end
end

main
